# http://docs.travis-ci.com/user/languages/r/
language: r

cache: packages

r:
  - release
  - devel

before_install:
  - sudo apt-get install -y libgdal-dev

after_success:
  - Rscript -e 'covr::coveralls(function_exclusions = c("\\.onLoad"))'

notifications:
  email:
  - zozlak@zozlak.org
  - sebastian.boeck@boku.ac.at
